// Generates src/styles/tokens.css: the Material 3 TonalSpot scheme for the brand seed,
// matching the Android client's ui/theme/Color.kt (including its fixed overrides).
// Usage: npm run theme (the color library's ESM build needs bundling to run in Node)
import { writeFile } from 'node:fs/promises';
import {
  Hct, SchemeTonalSpot, MaterialDynamicColors, argbFromHex, hexFromArgb,
} from '@material/material-color-utilities';

const SEED = '#5B6642';
const roles = [
  'primary', 'onPrimary', 'primaryContainer', 'onPrimaryContainer',
  'secondary', 'onSecondary', 'secondaryContainer', 'onSecondaryContainer',
  'error', 'onError', 'errorContainer', 'onErrorContainer',
  'background', 'onBackground', 'surface', 'onSurface', 'surfaceVariant', 'onSurfaceVariant',
  'surfaceContainerLowest', 'surfaceContainerLow', 'surfaceContainer', 'surfaceContainerHigh',
  'surfaceContainerHighest', 'inverseSurface', 'inverseOnSurface', 'inversePrimary', 'scrim',
];
// Fixed values the Android app deliberately uses instead of generated roles.
const overrides = {
  light: { tertiary: '#718053', onTertiary: '#FFFFFF', tertiaryContainer: '#323825', onTertiaryContainer: '#FFFFFF', outline: '#CCCCCC', outlineVariant: '#999999' },
  dark: { tertiary: '#5B6642', onTertiary: '#FFFFFF', tertiaryContainer: '#323825', onTertiaryContainer: '#FFFFFF', outline: '#3A3A3A', outlineVariant: '#ADADAD' },
};
const kebab = (s) => s.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase());

function block(isDark) {
  const scheme = new SchemeTonalSpot(Hct.fromInt(argbFromHex(SEED)), isDark, 0);
  const colors = new MaterialDynamicColors();
  const lines = roles.map((r) => {
    const dc = typeof colors[r] === 'function' ? colors[r]() : MaterialDynamicColors[r];
    return `  --md-${kebab(r)}: ${hexFromArgb(dc.getArgb(scheme))};`;
  });
  for (const [k, v] of Object.entries(overrides[isDark ? 'dark' : 'light'])) lines.push(`  --md-${kebab(k)}: ${v};`);
  lines.push(`  --md-primary-20: ${hexFromArgb(scheme.primaryPalette.tone(20))};`);
  lines.push(`  --md-primary-90: ${hexFromArgb(scheme.primaryPalette.tone(90))};`);
  lines.push(`  --md-secondary-40: ${hexFromArgb(scheme.secondaryPalette.tone(40))};`);
  lines.push(`  --md-neutral-70: ${hexFromArgb(scheme.neutralPalette.tone(70))};`);
  return lines.join('\n');
}

const css = `/* Generated by scripts/generate-theme.mjs — do not edit by hand. */
:root, [data-theme='light'] {
  color-scheme: light;
${block(false)}
}
[data-theme='dark'] {
  color-scheme: dark;
${block(true)}
}
`;
await writeFile('src/styles/tokens.css', css);
console.log('tokens.css written');
