// UI strings, taken from the Android client's res/values/strings.xml.
export const S = {
  appName: 'جام سخن',
  aboutUs: 'درباره ما',
  aboutBase: 'جام سخن یک اپلیکیشن متن باز است و هدف ما از توسعه آن، دسترسی راحت همه علاقه‌مندان به اشعار فارسی است.',
  aboutWebsite: 'برای آشنایی بیشتر با برنامه و سازندگان آن، به وب‌سایت ما سر بزنید.',
  aboutGithub: 'کد‌های این اپلیکیشن از طریق مخزن GitHub در دسترس عموم هستند.',
  aboutSupport: 'در صورت تمایل، می‌توانید از طریق هر یک از لینک‌های زیر از ما حمایت کنید.',
  aboutEmail: 'اگر تمایل دارید به هر نحوی به بهتر شدن این اپلیکیشن کمک کنید،‌ از طریق ایمیل jaamesokhan@gmail.com با ما در ارتباط باشید.',
  copyRight: 'منبع اشعار و خوانش‌های موجود در برنامه، پایگاه داده‌ی آزاد گنجور است.',
  aboutTitle: 'درباره جام سخن',
  supportTitle: 'حمایت از ما',
  contributionTitle: 'همکاری با ما',
  beSupportive: 'حامی باش',
  daramet: 'دارمت',
  website: 'سایت جام سخن',

  alreadyDownloaded: 'از قبل دانلود شده است!',
  downloadSuccessful: 'دانلود با موفقیت انجام شد.',
  downloadFailed: 'دانلود با مشکل مواجه شد!',
  noPoetDownloaded: 'هیچ شاعری دانلود نشده است!',
  poemNotAvailable: 'شعر یافت نشد!',
  noPoetFound: 'شاعری یافت نشد!',
  slowLoadHint: 'لطفاً کمی صبر کنید…',
  unbookmarkSuccess: 'با موفقیت حذف شد.',
  noBookmark: 'هنوز هیچ شعری ذخیره نکرده‌اید!',
  noHighlights: 'متنی را هایلایت نکرده‌اید!',
  recitationNotFound: 'هیچ خوانشی برای این شعر یافت نشد.',
  recitationFetchFailed: 'دریافت خوانش با خطا مواجه شد!',
  networkError: 'اتصال به اینترنت برقرار نیست!',

  addNewPoet: 'شاعر جدید',
  addNewPoetPageTitle: 'افزودن شاعر جدید',
  verseNumber: 'نمایش شماره بیت',
  removeVerseNumber: 'نمایش ندادن شماره بیت',
  recentSearches: 'جستجوهای اخیر',
  selectVerses: 'انتخاب مصرع',
  deletePoet: 'حذف شاعر',
  showHighlight: 'نمایش دادن هایلایت',
  dontShowHighlight: 'نمایش ندادن هایلایت',
  notePlaceholder: 'یادداشت خود را اینجا بنویسید …',
  highlight: 'هایلایت',
  copy: 'کپی',
  copied: 'کپی شد.',
  meaning: 'معنی',
  meaningNotFound: 'معنی این کلمه یافت نشد.',
  searchTitle: 'جست‌وجو در اشعار',
  dailyRandomPoemTitle: 'شعر تصادفی امروز',
  dailyRandomPoemNotification: 'دریافت شعر تصادفی روزانه',
  dailyRandomPoemNotificationDescription: 'هر روز در زمان انتخابی شما، یک شعر تصادفی دریافت کنید.',
  dailyRandomPoemTimeLabel: 'زمان ارسال اعلان:',
  dailyRandomPoemUnsupported:
    'مرورگر شما از اعلان‌های زمان‌بندی‌شده پشتیبانی نمی‌کند. برای این قابلیت، برنامه را روی Chrome یا Edge اندروید نصب کنید.',
  randomPoemCategorySelection: 'انتخاب دسته‌بندی‌های شعر تصادفی',
  randomPoemCategoryDescription: 'دسته‌بندی‌هایی را که مایلید در اشعار تصادفی لحاظ شوند، انتخاب کنید.',

  previous: 'قبلی',
  next: 'بعدی',
  comment: 'یادداشت',
  bookmarked: 'حذف از علاقه‌مندی',
  unbookmarked: 'اضافه به علاقه‌مندی‌ها',
  share: 'اشتراک گذاری',
  cancel: 'لغو',
  delete: 'حذف',
  deleteAllHistory: 'حذف همه',
  close: 'بستن',
  back: 'بازگشت',
  randomPoem: 'شعر تصادفی',
  randomPoemOptions: 'تنظیمات شعر تصادفی',
  randomPoemLayout: 'چیدمان شعر تصادفی',
  randomPoemAnother: 'شعر دیگر',
  randomPoemLayoutIntroTitle: 'چیدمان برای شعر تصادفی',
  randomPoemLayoutIntroBody: 'می‌توانید ظاهر کارت شعر تصادفی صفحه اصلی را از میان چند طرح انتخاب کنید، یا آن را کاملاً پنهان کنید.',
  randomPoemLayoutIntroConfirm: 'انتخاب چیدمان',
  randomPoemLayoutIntroDismiss: 'بعداً',
  introToFriend: 'معرفی به دوستان',
  options: 'گزینه‌ها',
  submit: 'ثبت',
  searchBarHint: 'دنبال چه شعری می‌گردید؟',
  search: 'جست‌وجو',
  viewPoem: 'مشاهده شعر',
  poetSearchBarHint: 'دنبال کدام شاعر می‌گردید؟',
  noteTitle: 'یادداشت‌ها',
  bookmarkTitle: 'ذخیره‌ها',
  highlightTitle: 'هایلایت‌ها',
  myPoetsTitle: 'اشعار من',
  searchAllPoets: 'همه شاعران',
  notFound: 'هیچ موردی یافت نشد!',
  searchLimitReached: 'فقط ۳۰۰ نتیجه اول نمایش داده می‌شود. جست‌وجو را دقیق‌تر کنید.',
  recite: 'خوانش',
  repeat: 'تکرار خوانش',
  playbackSpeed: 'سرعت پخش',
  settings: 'تنظیمات',
  appTheme: 'تم برنامه',
  font: 'فونت',
  fontSize: 'اندازه قلم',
  resetToDefault: 'بازگشت به پیش‌فرض',
  noNote: 'هنوز هیچ یادداشتی ندارید!',
  noHistory: 'هیچ شعری مطالعه نکرده‌اید!',
  readHistory: 'آخرین اشعار مطالعه شده',
  deleteHighlightSuccess: 'هایلایت با موفقیت حذف شد.',
  downloadPoet: 'افزودن',
  openDownloadedPoet: 'باز کردن',
  downloadNewPoet: 'افزودن شاعر جدید',
  highlightHint: 'برای مشاهده معنی کلمات یا هایلایت کردن، متن را انتخاب کنید.',
  category: 'دسته‌بندی',
  poem: 'شعر',

  addToCategory: 'افزودن به دسته‌بندی',
  addToCategoryPill: 'افزودن به دسته',
  goToPoem: 'رفتن به شعر',
  categories: 'دسته‌بندی‌ها',
  manageCategoriesSave: 'دسته‌بندی ذخیره‌ها',
  manageCategoriesHighlight: 'دسته‌بندی هایلایت‌ها',
  newCategory: 'دسته‌بندی جدید',
  editCategory: 'ویرایش دسته',
  categoryNameLabel: 'نام دسته',
  categoryNameHint: 'مثلاً: شب‌های زمستان',
  colorLabel: 'رنگ',
  confirm: 'تأیید',
  allCategoriesChip: 'همه',
  emptyCategoryTitle: 'هنوز چیزی در این دسته نیست',
  emptyCategorySubtitle: 'از منوی هر مورد، آن را به این دسته اضافه کنید.',
  categoryCreated: 'دسته‌بندی ساخته شد.',
  categoryEdited: 'دسته‌بندی ویرایش شد.',
  categoryDeleted: 'دسته‌بندی حذف شد.',
  savedToCategory: 'ذخیره شد.',
  saveMomentTitle: 'در کدام دسته ذخیره شود؟',
  newCategoryChip: 'دسته جدید',
  save: 'ذخیره',

  storage: 'ذخیره‌سازی',
  storagePersistent: 'داده‌های شما به صورت ماندگار روی این دستگاه ذخیره می‌شوند.',
  storageBestEffort: 'مرورگر ممکن است در صورت کمبود فضا داده‌ها را پاک کند. برای اطمینان، برنامه را نصب کنید یا از داده‌ها پشتیبان بگیرید.',
  storageMemory: 'این مرورگر ذخیره‌سازی دائمی را پشتیبانی نمی‌کند؛ داده‌ها با بستن برنامه پاک می‌شوند.',
  storageUsage: 'فضای مصرف‌شده',
  backupExport: 'دریافت فایل پشتیبان',
  backupImport: 'بازگردانی از فایل پشتیبان',
  backupImportConfirm: 'همه داده‌های فعلی با محتوای فایل پشتیبان جایگزین می‌شوند. ادامه می‌دهید؟',
  backupImported: 'پشتیبان بازگردانی شد.',
  backupFailed: 'بازگردانی پشتیبان ناموفق بود!',
  installApp: 'نصب برنامه',
  installAppDescription: 'جام سخن را مثل یک برنامه روی دستگاه خود نصب کنید تا آفلاین هم در دسترس باشد.',
  updateAvailable: 'نسخه جدید برنامه آماده است.',
  update: 'به‌روزرسانی',
  offlineReady: 'برنامه برای استفاده آفلاین آماده است.',
  deletePoetConfirm: (name: string) => `«${name}» و همه ذخیره‌ها، هایلایت‌ها و یادداشت‌های اشعارش حذف شود؟`,
  clearHistoryConfirm: 'همه سوابق مطالعه حذف شود؟',
  deleteCategoryConfirm: (name: string) => `دسته «${name}» حذف شود؟`,
  importing: 'در حال افزودن اشعار…',
  downloading: 'در حال دریافت…',
  verses: 'بیت',
  poemsCount: (n: string) => `${n} شعر`,
  noRecitation: 'بدون خوانش',
  pause: 'مکث',
  play: 'پخش',
  stop: 'توقف',
  seekForward: 'جلو',
  seekBackward: 'عقب',

  introToFriendsText:
    'جام سخن\nاپلیکیشن متن باز برای دسترسی آسان به اشعار فارسی.\n\n«جام سخن» در بازار:\nhttp://cafebazaar.ir/app/?id=ir.jaamebaade.jaamebaade_client&ref=share\n\n«جام سخن» در مایکت:\nhttps://myket.ir/app/ir.jaamebaade.jaamebaade_client\n\nنسخه وب:\n',

  settingVerses: [
    ['سخن ماند از تو همی یادگار', 'سخن را چنین خوارمایه مدار'],
    ['فریدون فرخ فرشته نبود', 'زمشک و ز عنبر سرشته نبود'],
    ['به داد و دهش یافت آن نیکویی', 'تو دادو دهش کن فریدون تویی'],
  ],
} as const;

export const LINKS = {
  github: 'https://github.com/jaamebaade/jaamebaade-client',
  hamibash: 'https://hamibash.com/jaamesokhan',
  daramet: 'https://daramet.com/jaamesokhan',
  website: 'https://jaamesokhan.ir',
  email: 'mailto:jaamesokhan@gmail.com',
};
